// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dcbqzhfireixiaafxqzj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRjYnF6aGZpcmVpeGlhYWZ4cXpqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4NDU0MDgsImV4cCI6MjA3MDQyMTQwOH0.4PICcj1T07zW0KC3asBXl9QtRI5o8HXIC-dSL6ed3DE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});